.Dd February 11, 2018
.Dt RFC-TO-BIB 1
.Os rfc-to-bib 0.2.2
.\" @link <http://manpages.bsd.lv/mdoc.html>
.\"
.Sh NAME
.\" ====
.Nm rfc-to-bib
.Nd generate IETF RFC BibTeX records
.\"
.Sh SYNOPSIS
.\" ========
.Nm
.\"
.Sh DESCRIPTION
.\" ===========
A library and CLI tool to generate BibTeX records for IETF RFCs.
.\"
.Sh EXIT STATUS
.\" ===========
.Ex -std
.\"
.Sh EXAMPLES
.\" ========
The following examples are shown as given to the shell:
.Pp
.Bd -literal -offset indent -compact
rfc-to-bib 2616 # Print BibTeX to stdout.

rfc-to-bib 2616 > rfc2616.bib # Write BibTeX to file.
.Ed
.\"
.Sh AUTHORS
.\" =======
.An James Benner Aq Mt james.benner@gmail.com
